### PR TITLE
Binning Service Tutorials

### PR DESCRIPTION
**Pull request by bparrello**
Updated metagenomic-binning submit tutorial, added metagenomic-binning output tutorial.

### CODE REVIEW

**Comment by olsonanl** [comment]
I'm not seeing that second tutorial metagenomic_output.rst in the index - is there an index change needed by Harry ?

**Comment by hyoo** [comment]
this is available now. maybe during the time i merged but not build yet. 

http://docs.patricbrc.org/tutorial/metagenomic_binning/metagenomic_output.html

**Comment by bparrello** [comment]
I have it in docroot/tutorial/index.rst. Does it need to be someplace else as well?

**Comment by olsonanl** [comment]
Looks like it is there now

On Dec 13, 2017, at 6:48 AM, Bruce Parrello <notifications@github.com<mailto:notifications@github.com>> wrote:

I have it in docroot/tutorial/index.rst. Does it need to be someplace else as well?

**Pull request merged**
